Feature/card view
DeveloperAcademy-POSTECH/MC3-Team11-Naughtya pull request #7
Opened 2023-07-23 15:10 UTC by Greeddk

카드뷰 즐겨찾기(북마크) 기능 활성화
북마크 되었을때, 해당 프로젝트가 위로 가게 설정 완료

2023-07-23 15:14 UTC, byoth commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +
근데 기획상 selected와 bookmarked가 동일한 개념인 거 같은데
figma에서 최신 시안 확인해주시면 좋을거 같습니다!

2023-07-23 15:18 UTC, byoth requested changes

2023-07-23 15:18 UTC, byoth commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +    }
근데 기획상 selected와 bookmarked가 동일한 개념인 거 같은데
figma에서 최신 시안 확인해주시면 좋을거 같습니다!

2023-07-23 15:18 UTC, byoth commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectAddModal/ProjectSetModalView.swift
> +        .frame(width: 421)
width를 고정시키면 앱을 리사이징했을 때 의도하지 않은 비율이 나올 것 같아요
section width를 따라가게 만들거나
최소한 width 대신 maxWidth로 사용해주시는 게 나을 것 같습니다

2023-07-23 15:18 UTC, byoth commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectAddModal/ProjectSetModalView.swift
> +    var isBookmarked: Bool = false
프로젝트 생성 시에 selected 여부는 항상 같을 거 같은데 뷰에서 변수로 관리할 필요가 있을까요?

2023-07-24 03:48 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +        defer { Self.projectStore.update() }
https://github.com/DeveloperAcademy-POSTECH/MC3-Team11-Naughtya/blob/bc5118c22ee622a3a9ea9b3f459a77100e353149/Naughtya/Projects/Features/CoreFeature/Sources/Domain/Stores/ProjectStore.swift#L19-L21

값이 Binding이 되어있다면...자동으로 update가 될터인데 Store에서 objectWillChange.send()를 수동으로 실행해줘야하는 이유가 있나요?
오히려 이부분이 나중에 버그로 만들어지지 않을까 조금 우려가 됩..니다... 😢 ...

2023-07-24 03:50 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +    }
> 

다릅니다. 기획 상 프로젝트 카드를 클릭했을 경우는 해당하는 프로젝트 별 투두 리스트가 프로젝트 투두 리스트뷰에 뜨는 기획이고
북마크는 프로젝트 리스트 뷰에서 다른 프로젝트들 보다 먼저 나타나는 고정핀 같은 역할을 하는거예요

2023-07-24 03:50 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectAddModal/ProjectSetModalView.swift
> +        .frame(width: 421)
요건 다시 만져보겠습니다

2023-07-24 03:51 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectAddModal/ProjectSetModalView.swift
> +    var isBookmarked: Bool = false
저는 여기서 만들어야 배열에 추가할때 추가되는지 알았어요. 변수로 관리하지 않아도 기본 값으로 넣어둘 수 있다는 말이죠?

2023-07-24 04:03 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +        project.isSelected = isSelected
이렇게 property별로 method를 만드는 것보다 각 property들에 method 실행을 binding시킨다면,
**더 Combine스럽게 구현이 될 것이라 생각해요.**

받은 project를 왜 그대로 return하는지도 궁금합니다.. ! 🤔 ....!!


**1. Subject와 sink method를 활용하면 아래와 같이 method 없이도 구현이 가능해보여요!**
```swift
import Combine

struct Store {
    func update() {}
}

struct Model {
    let isToggled: CurrentValueSubject<Bool, Never>
    private let store = Store()
    private var cancellables = Set<AnyCancellable>()

    init(isToggled: Bool = false) {
        self.isToggled = CurrentValueSubject<Bool, Never>(isToggled)

        self.isToggled
            .sink { [self] _ in
                self.store.update()
            }
            .store(in: &cancellables)
    }
}
```

**2. Combine을 활용하지 않고, didSet만 활용해도 method 없이 비슷한 것도 가능해요!**
```
struct Model {
    var isToggled: Bool {
        didSet {
            store.update()
        }
    }

    private let store = Store()

    init(isToggled: Bool = false) {
        self.isToggled = isToggled
    }
}
```

지금 코드는 UIKit 시대의 Rx/Combine 고려 없이 만들어진 느낌이 강해서 한 번 꼭 고민해볼 필요가 있어보여서 길게 코멘트 남겨보아요!!

2023-07-24 04:05 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +        project.endedAt!
강제 언래핑이어도 될까요 ㅜㅜㅜㅜㅜ !!

2023-07-24 04:06 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +    }
이 내부에서만 사용된 값들인데 별도의 변수들로 정의되어야하는 이유가 있을까요 ... ?????

2023-07-24 04:07 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +    let cornerRadius: CGFloat = 16
struct 내부 property들의 접근제한자의 점검을 해보면 좋을 것 같습니당 ㅎㅎ

2023-07-24 04:07 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +    }
```suggestion
    }
    
```

2023-07-24 04:08 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +// }
```suggestion
```

 주석은 삭제하는 것을 추천드려요 : )
꼭 남겨야한다면 이유를 작성해주세요 ~

2023-07-24 04:12 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +}
View struct에 Logic적인 코드가 들어가도 될까요 ?
이 View에서만 사용된다면 fileprivate extension 등으로 분리되는 것이 적절해보여요 ~

```swift
struct CardView: View {
    // ...
}

fileprivate extension Calendar {
    var dDay: String {
        let calendar = Self.current
        let currentDate = calendar.startOfDay(for: Date())
        let projectEndDate = calendar.startOfDay(for: projectEndDay)

        let components = calendar.dateComponents([.day], from: currentDate, to: projectEndDate)

        guard let days = components.day else { return "날짜 계산 오류" }

        if days == 0 {
            return "D-day"
        } else if days > 0 {
            return "D-\(days)"
        } else {
            return "D+\(-days)"
        }
    }
}
```

2023-07-24 04:13 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectList/ProjectListView.swift
> +        self.projects = projects.sorted { $0.isBookmarked && !$1.isBookmarked }
👍 👍

2023-07-24 04:45 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +        project.isSelected = isSelected
이런 인사이트 감사합니다!! ㅎㅎ 뵤랑 이야기해보고 적용해보도록 하겠습니다.
아 그전에 사실 저건 목업데이터라서 임시용이고 코어데이터를 적용하면 어떻게 바뀔지 모르겠어요

2023-07-24 04:46 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +// }
넵 삭제하겠습니다!

2023-07-24 04:46 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +}
전 이런게 있는줄 처음 알았답니다 호호... 덕분에 하나 더 알아가요! 수정해보겠습니다.

2023-07-24 05:23 UTC, byoth commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectAddModal/ProjectSetModalView.swift
> +    var isBookmarked: Bool = false
네 필수는 아닌거 같습니당

2023-07-24 07:31 UTC, byoth commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +        defer { Self.projectStore.update() }
같은 데이터가 여러 뷰에 공유되는 저희 기획 특성상 데이터를 레퍼런스 타입으로 사용하고 싶어서 class 기반으로 구성되어 있는데
@State나 @Published의 경우 클래스의 프로퍼티 변화를 변화로 인식하지 않아서 수동으로 objectWillChange를 알려야 할 필요가 있었습니다
비효율적인 부분은 인식하고 있지만 데이터를 struct 기반으로 구성하는 것보다는 리스크가 적겠다는 판단으로 이렇게 진행했는데
혹시 다른 인사이트 있으실까요?

2023-07-24 07:36 UTC, byoth commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +        project.isSelected = isSelected
Combine이나 didSet으로 각 프로퍼티의 변화에 모두 대응하기에는 프로퍼티가 너무 많은 문제도 있었습니다
그렇다고 데이터를 변화시키는 행위 마다 update를 호출하는 것 역시 행위가 너무 많은 문제가 있지만
어떤 게 나을지는 잘 모르겠어서 일단 Entity를 무겁지 않게 하는 방향을 선택했습니다

2023-07-24 07:51 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +        project.isSelected = isSelected
> Combine이나 didSet으로 각 프로퍼티의 변화에 모두 대응하기에는 프로퍼티가 너무 많은 문제도 있었습니다

저는 해당 프로퍼티마다 method가 있다는 것이 또 다른 문제를 야기한다고 생각되어요.
특히 저 코드를 처음 사용하는 사람은 method를 사용해서 값을 변경해야한다는 것을 모르는 상황에서는 또다른 side effect의 위험성이 너무 높기도하구요. 
SwiftUI를 전제로한다면 선언형이 아니라 너무 명령형에 가깝지않나 싶기도해요.

2023-07-24 18:18 UTC, byoth commented on Naughtya/Projects/Features/CoreFeature/Sources/Domain/UseCases/Mocks/MockProjectUseCase.swift
> +        project.isSelected = isSelected
프로퍼티마다 method가 있는 건 아니고 기획상 "액션"이 될 수 있는 것의 기준으로 method가 있긴 합니다
하지만 언급해주신대로 method를 사용하지 않고 값을 변경하게 되는 경우의 side effect, 명령형스럽다는 피드백은 동의합니다!
그러면서도 데이터 모델인 entity들이 이들을 관리하고 있는 store를 조작할 수 있게 된다는 점에서
제가 의도한 의존성 방향에 어긋나서 조금 더 생각해봐야겠지만 Combine으로 이 문제를 풀어내는 방향은 좋을 것 같아요!
+ 각 프로퍼티를 combineLatest 같은 operator로 묶어 사용하면 더 좋을 것 같네요

2023-07-25 06:08 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +        project.endedAt!
> 강제 언래핑이어도 될까요 ㅜㅜㅜㅜㅜ !!
이건 기획 상 무기한으로 둘 수도 있어서.. 논의 후 처리를 하겠습니다!

2023-07-25 06:10 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +    }
> 이 내부에서만 사용된 값들인데 별도의 변수들로 정의되어야하는 이유가 있을까요 ... ?????

따로 변수로 정의하지 않고 바로 써도 되서 그렇게 말하신건가요?

2023-07-25 06:33 UTC, unnnyong commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +    }
네네 맞습니다!!!!!!!!!!!!!

2023-07-25 06:38 UTC, byoth commented
@Greeddk conflict 났는데 해결해보신적 있으신가요? 제가 할까요?

2023-07-25 06:40 UTC, Greeddk commented on Naughtya/Projects/Features/CoreFeature/Sources/Presentation/Views/ProjectCardView/ProjectCardView.swift
> +    }
> 네네 맞습니다!!!!!!!!!!!!!

수정했슴다 핳

2023-07-25 06:41 UTC, Greeddk commented
> @Greeddk conflict 났는데 해결해보신적 있으신가요? 제가 할까요?

해보고싶지만 옆에 뵤가 없으시다면 힘들거 같네요. 다음에 해보겠습니다

2023-07-25 07:14 UTC, byoth approved these changes

2023-07-25 07:14 UTC, byoth commented
고생하셨습니다

2023-07-25 07:14 UTC, merged